name: Deployments

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/**


jobs:
  build-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Build with maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY}}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_TEST_BUCKET_NAME: ${{ secrets.AWS_TEST_BUCKET_NAME }}
          CLIENT_BASE_URL: ${{ secrets.CLIENT_BASE_URL }}
        working-directory: ./backend
        run: mvn -B package
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/el-shop:latest
  deploy-to-droplet:
    runs-on: ubuntu-20.04
    needs: build-backend
    steps:
      - name: connect with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /el-shop/backend
            docker stop el-shop
            docker rm el-shop
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/el-shop:latest
            docker run -d --name el-shop -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/el-shop:latest